<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("user_overtime/index", "Go Back")); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(array("user_overtime/new", "Create ")); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Date</th>
            <th>Overtime Of Amount</th>
            <th>Overtime Of Unit</th>
            <th>Project Of Name</th>
            <th>User</th>
            <th>Approved</th>
            <th>Approved Of By</th>
            <th>Approve Of Date</th>
            <th>Created</th>
            <th>Updated</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $user_overtime): ?>
            <tr>
                <td><?php echo $user_overtime->id ?></td>
            <td><?php echo $user_overtime->date ?></td>
            <td><?php echo $user_overtime->overtime_amount ?></td>
            <td><?php echo $user_overtime->overtime_unit_id ?></td>
            <td><?php echo $user_overtime->project_name ?></td>
            <td><?php echo $user_overtime->user_id ?></td>
            <td><?php echo $user_overtime->approved ?></td>
            <td><?php echo $user_overtime->approved_by ?></td>
            <td><?php echo $user_overtime->approve_date ?></td>
            <td><?php echo $user_overtime->created_at ?></td>
            <td><?php echo $user_overtime->updated_at ?></td>

                <td><?php echo $this->tag->linkTo(array("user_overtime/edit/" . $user_overtime->id, "Edit")); ?></td>
                <td><?php echo $this->tag->linkTo(array("user_overtime/delete/" . $user_overtime->id, "Delete")); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("user_overtime/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("user_overtime/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("user_overtime/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("user_overtime/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
