<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("user_overtime", "Back")) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit user_overtime
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "user_overtime/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldDate" class="col-sm-2 control-label">Date</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("date", "size" => 30, "class" => "form-control", "id" => "fieldDate")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldOvertimeAmount" class="col-sm-2 control-label">Overtime Of Amount</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("overtime_amount", "type" => "number", "class" => "form-control", "id" => "fieldOvertimeAmount")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldOvertimeUnitId" class="col-sm-2 control-label">Overtime Of Unit</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("overtime_unit_id", "type" => "number", "class" => "form-control", "id" => "fieldOvertimeUnitId")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldProjectName" class="col-sm-2 control-label">Project Of Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("project_name", "size" => 30, "class" => "form-control", "id" => "fieldProjectName")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUserId" class="col-sm-2 control-label">User</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("user_id", "type" => "number", "class" => "form-control", "id" => "fieldUserId")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldApproved" class="col-sm-2 control-label">Approved</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("approved", "type" => "number", "class" => "form-control", "id" => "fieldApproved")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldApprovedBy" class="col-sm-2 control-label">Approved Of By</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("approved_by", "type" => "number", "class" => "form-control", "id" => "fieldApprovedBy")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldApproveDate" class="col-sm-2 control-label">Approve Of Date</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("approve_date", "size" => 30, "class" => "form-control", "id" => "fieldApproveDate")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCreatedAt" class="col-sm-2 control-label">Created</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("created_at", "size" => 30, "class" => "form-control", "id" => "fieldCreatedAt")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUpdatedAt" class="col-sm-2 control-label">Updated</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("updated_at", "size" => 30, "class" => "form-control", "id" => "fieldUpdatedAt")) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Save", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
